# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/Qt4_catsmaintwidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CatsMaintWidget(object):
    def setupUi(self, CatsMaintWidget):
        CatsMaintWidget.setObjectName(_fromUtf8("CatsMaintWidget"))
        CatsMaintWidget.resize(1230, 855)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CatsMaintWidget.sizePolicy().hasHeightForWidth())
        CatsMaintWidget.setSizePolicy(sizePolicy)
        self.vboxlayout = QtGui.QVBoxLayout(CatsMaintWidget)
        self.vboxlayout.setMargin(11)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.groupBox5 = QtGui.QGroupBox(CatsMaintWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox5.sizePolicy().hasHeightForWidth())
        self.groupBox5.setSizePolicy(sizePolicy)
        self.groupBox5.setObjectName(_fromUtf8("groupBox5"))
        self.hboxlayout = QtGui.QHBoxLayout(self.groupBox5)
        self.hboxlayout.setMargin(11)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.lblPowerState = QtGui.QLabel(self.groupBox5)
        self.lblPowerState.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPowerState.setWordWrap(False)
        self.lblPowerState.setObjectName(_fromUtf8("lblPowerState"))
        self.hboxlayout.addWidget(self.lblPowerState)
        self.btPowerOn = QtGui.QPushButton(self.groupBox5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPowerOn.sizePolicy().hasHeightForWidth())
        self.btPowerOn.setSizePolicy(sizePolicy)
        self.btPowerOn.setObjectName(_fromUtf8("btPowerOn"))
        self.hboxlayout.addWidget(self.btPowerOn)
        self.btPowerOff = QtGui.QPushButton(self.groupBox5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPowerOff.sizePolicy().hasHeightForWidth())
        self.btPowerOff.setSizePolicy(sizePolicy)
        self.btPowerOff.setObjectName(_fromUtf8("btPowerOff"))
        self.hboxlayout.addWidget(self.btPowerOff)
        self.vboxlayout.addWidget(self.groupBox5)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(11)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.groupBox2 = QtGui.QGroupBox(CatsMaintWidget)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox2)
        self.vboxlayout1.setMargin(11)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.btLid1Open = QtGui.QPushButton(self.groupBox2)
        font = QtGui.QFont()
        self.btLid1Open.setFont(font)
        self.btLid1Open.setObjectName(_fromUtf8("btLid1Open"))
        self.vboxlayout1.addWidget(self.btLid1Open)
        self.btLid1Close = QtGui.QPushButton(self.groupBox2)
        font = QtGui.QFont()
        self.btLid1Close.setFont(font)
        self.btLid1Close.setObjectName(_fromUtf8("btLid1Close"))
        self.vboxlayout1.addWidget(self.btLid1Close)
        self.hboxlayout1.addWidget(self.groupBox2)
        self.groupBox2_2 = QtGui.QGroupBox(CatsMaintWidget)
        self.groupBox2_2.setObjectName(_fromUtf8("groupBox2_2"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.groupBox2_2)
        self.vboxlayout2.setMargin(11)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.btLid2Open = QtGui.QPushButton(self.groupBox2_2)
        font = QtGui.QFont()
        self.btLid2Open.setFont(font)
        self.btLid2Open.setObjectName(_fromUtf8("btLid2Open"))
        self.vboxlayout2.addWidget(self.btLid2Open)
        self.btLid2Close = QtGui.QPushButton(self.groupBox2_2)
        font = QtGui.QFont()
        self.btLid2Close.setFont(font)
        self.btLid2Close.setObjectName(_fromUtf8("btLid2Close"))
        self.vboxlayout2.addWidget(self.btLid2Close)
        self.hboxlayout1.addWidget(self.groupBox2_2)
        self.groupBox2_2_2 = QtGui.QGroupBox(CatsMaintWidget)
        self.groupBox2_2_2.setObjectName(_fromUtf8("groupBox2_2_2"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.groupBox2_2_2)
        self.vboxlayout3.setMargin(11)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.btLid3Open = QtGui.QPushButton(self.groupBox2_2_2)
        font = QtGui.QFont()
        self.btLid3Open.setFont(font)
        self.btLid3Open.setObjectName(_fromUtf8("btLid3Open"))
        self.vboxlayout3.addWidget(self.btLid3Open)
        self.btLid3Close = QtGui.QPushButton(self.groupBox2_2_2)
        font = QtGui.QFont()
        self.btLid3Close.setFont(font)
        self.btLid3Close.setObjectName(_fromUtf8("btLid3Close"))
        self.vboxlayout3.addWidget(self.btLid3Close)
        self.hboxlayout1.addWidget(self.groupBox2_2_2)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.groupBox6 = QtGui.QGroupBox(CatsMaintWidget)
        self.groupBox6.setObjectName(_fromUtf8("groupBox6"))
        self.hboxlayout2 = QtGui.QHBoxLayout(self.groupBox6)
        self.hboxlayout2.setMargin(11)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.lblMessage = QtGui.QLabel(self.groupBox6)
        self.lblMessage.setWordWrap(False)
        self.lblMessage.setObjectName(_fromUtf8("lblMessage"))
        self.hboxlayout2.addWidget(self.lblMessage)
        self.vboxlayout.addWidget(self.groupBox6)
        self.groupBox = QtGui.QGroupBox(CatsMaintWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btSoakTool = QtGui.QPushButton(self.groupBox)
        self.btSoakTool.setObjectName(_fromUtf8("btSoakTool"))
        self.horizontalLayout.addWidget(self.btSoakTool)
        self.btDryTool = QtGui.QPushButton(self.groupBox)
        self.btDryTool.setObjectName(_fromUtf8("btDryTool"))
        self.horizontalLayout.addWidget(self.btDryTool)
        spacerItem = QtGui.QSpacerItem(890, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.vboxlayout.addWidget(self.groupBox)
        self.groupBox13 = QtGui.QGroupBox(CatsMaintWidget)
        self.groupBox13.setObjectName(_fromUtf8("groupBox13"))
        self.hboxlayout3 = QtGui.QHBoxLayout(self.groupBox13)
        self.hboxlayout3.setMargin(11)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.btAbort = QtGui.QPushButton(self.groupBox13)
        self.btAbort.setObjectName(_fromUtf8("btAbort"))
        self.hboxlayout3.addWidget(self.btAbort)
        self.btSafe = QtGui.QPushButton(self.groupBox13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btSafe.sizePolicy().hasHeightForWidth())
        self.btSafe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.btSafe.setFont(font)
        self.btSafe.setObjectName(_fromUtf8("btSafe"))
        self.hboxlayout3.addWidget(self.btSafe)
        self.btBackToolA = QtGui.QPushButton(self.groupBox13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btBackToolA.sizePolicy().hasHeightForWidth())
        self.btBackToolA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.btBackToolA.setFont(font)
        self.btBackToolA.setObjectName(_fromUtf8("btBackToolA"))
        self.hboxlayout3.addWidget(self.btBackToolA)
        self.btBackToolB = QtGui.QPushButton(self.groupBox13)
        self.btBackToolB.setObjectName(_fromUtf8("btBackToolB"))
        self.hboxlayout3.addWidget(self.btBackToolB)
        self.btResetError = QtGui.QPushButton(self.groupBox13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btResetError.sizePolicy().hasHeightForWidth())
        self.btResetError.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.btResetError.setFont(font)
        self.btResetError.setObjectName(_fromUtf8("btResetError"))
        self.hboxlayout3.addWidget(self.btResetError)
        self.vboxlayout.addWidget(self.groupBox13)
        self.groupBox5_2 = QtGui.QGroupBox(CatsMaintWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox5_2.sizePolicy().hasHeightForWidth())
        self.groupBox5_2.setSizePolicy(sizePolicy)
        self.groupBox5_2.setObjectName(_fromUtf8("groupBox5_2"))
        self.hboxlayout4 = QtGui.QHBoxLayout(self.groupBox5_2)
        self.hboxlayout4.setMargin(11)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.lblRegulationState = QtGui.QLabel(self.groupBox5_2)
        self.lblRegulationState.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRegulationState.setWordWrap(False)
        self.lblRegulationState.setObjectName(_fromUtf8("lblRegulationState"))
        self.hboxlayout4.addWidget(self.lblRegulationState)
        self.btRegulationOn = QtGui.QPushButton(self.groupBox5_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btRegulationOn.sizePolicy().hasHeightForWidth())
        self.btRegulationOn.setSizePolicy(sizePolicy)
        self.btRegulationOn.setObjectName(_fromUtf8("btRegulationOn"))
        self.hboxlayout4.addWidget(self.btRegulationOn)
        self.vboxlayout.addWidget(self.groupBox5_2)

        self.retranslateUi(CatsMaintWidget)
        QtCore.QMetaObject.connectSlotsByName(CatsMaintWidget)
        CatsMaintWidget.setTabOrder(self.btPowerOn, self.btPowerOff)
        CatsMaintWidget.setTabOrder(self.btPowerOff, self.btLid1Open)
        CatsMaintWidget.setTabOrder(self.btLid1Open, self.btLid1Close)
        CatsMaintWidget.setTabOrder(self.btLid1Close, self.btLid2Open)
        CatsMaintWidget.setTabOrder(self.btLid2Open, self.btLid2Close)
        CatsMaintWidget.setTabOrder(self.btLid2Close, self.btLid3Open)
        CatsMaintWidget.setTabOrder(self.btLid3Open, self.btLid3Close)
        CatsMaintWidget.setTabOrder(self.btLid3Close, self.btBackToolA)

    def retranslateUi(self, CatsMaintWidget):
        CatsMaintWidget.setWindowTitle(_translate("CatsMaintWidget", "Form1", None))
        self.groupBox5.setTitle(_translate("CatsMaintWidget", "Arm Power", None))
        self.lblPowerState.setText(_translate("CatsMaintWidget", "Power", None))
        self.btPowerOn.setText(_translate("CatsMaintWidget", "Power On", None))
        self.btPowerOff.setText(_translate("CatsMaintWidget", "Power Off", None))
        self.groupBox2.setTitle(_translate("CatsMaintWidget", "Lid 1", None))
        self.btLid1Open.setText(_translate("CatsMaintWidget", "Open", None))
        self.btLid1Close.setText(_translate("CatsMaintWidget", "Close", None))
        self.groupBox2_2.setTitle(_translate("CatsMaintWidget", "Lid 2", None))
        self.btLid2Open.setText(_translate("CatsMaintWidget", "Open", None))
        self.btLid2Close.setText(_translate("CatsMaintWidget", "Close", None))
        self.groupBox2_2_2.setTitle(_translate("CatsMaintWidget", "Lid 3", None))
        self.btLid3Open.setText(_translate("CatsMaintWidget", "Open", None))
        self.btLid3Close.setText(_translate("CatsMaintWidget", "Close", None))
        self.groupBox6.setTitle(_translate("CatsMaintWidget", "CATS message", None))
        self.lblMessage.setText(_translate("CatsMaintWidget", "Dummy message", None))
        self.groupBox.setTitle(_translate("CatsMaintWidget", "Maintenance commands", None))
        self.btSoakTool.setText(_translate("CatsMaintWidget", "Soak (remove blue plug!)", None))
        self.btDryTool.setText(_translate("CatsMaintWidget", "Dry", None))
        self.groupBox13.setTitle(_translate("CatsMaintWidget", "Recovery Commands", None))
        self.btAbort.setText(_translate("CatsMaintWidget", "Abort", None))
        self.btSafe.setText(_translate("CatsMaintWidget", "Safe", None))
        self.btBackToolA.setText(_translate("CatsMaintWidget", "Back (Tool A)", None))
        self.btBackToolB.setText(_translate("CatsMaintWidget", "Back (Tool B)", None))
        self.btResetError.setText(_translate("CatsMaintWidget", "Reset Error", None))
        self.groupBox5_2.setTitle(_translate("CatsMaintWidget", "LN2 Regulation", None))
        self.lblRegulationState.setText(_translate("CatsMaintWidget", "Regulation", None))
        self.btRegulationOn.setText(_translate("CatsMaintWidget", "Regulation On", None))

