# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/Qt4_isara2maintwidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Isara2MaintWidget(object):
    def setupUi(self, Isara2MaintWidget):
        Isara2MaintWidget.setObjectName(_fromUtf8("Isara2MaintWidget"))
        Isara2MaintWidget.resize(1230, 855)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Isara2MaintWidget.sizePolicy().hasHeightForWidth())
        Isara2MaintWidget.setSizePolicy(sizePolicy)
        self.vboxlayout = QtGui.QVBoxLayout(Isara2MaintWidget)
        self.vboxlayout.setMargin(11)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.groupBox5 = QtGui.QGroupBox(Isara2MaintWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox5.sizePolicy().hasHeightForWidth())
        self.groupBox5.setSizePolicy(sizePolicy)
        self.groupBox5.setObjectName(_fromUtf8("groupBox5"))
        self.hboxlayout = QtGui.QHBoxLayout(self.groupBox5)
        self.hboxlayout.setMargin(11)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.lblPowerState = QtGui.QLabel(self.groupBox5)
        self.lblPowerState.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPowerState.setWordWrap(False)
        self.lblPowerState.setObjectName(_fromUtf8("lblPowerState"))
        self.hboxlayout.addWidget(self.lblPowerState)
        self.btPowerOn = QtGui.QPushButton(self.groupBox5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPowerOn.sizePolicy().hasHeightForWidth())
        self.btPowerOn.setSizePolicy(sizePolicy)
        self.btPowerOn.setObjectName(_fromUtf8("btPowerOn"))
        self.hboxlayout.addWidget(self.btPowerOn)
        self.btPowerOff = QtGui.QPushButton(self.groupBox5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btPowerOff.sizePolicy().hasHeightForWidth())
        self.btPowerOff.setSizePolicy(sizePolicy)
        self.btPowerOff.setObjectName(_fromUtf8("btPowerOff"))
        self.hboxlayout.addWidget(self.btPowerOff)
        self.vboxlayout.addWidget(self.groupBox5)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(11)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.groupBox2 = QtGui.QGroupBox(Isara2MaintWidget)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox2)
        self.vboxlayout1.setMargin(11)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.btLid1Open = QtGui.QPushButton(self.groupBox2)
        font = QtGui.QFont()
        self.btLid1Open.setFont(font)
        self.btLid1Open.setObjectName(_fromUtf8("btLid1Open"))
        self.vboxlayout1.addWidget(self.btLid1Open)
        self.btLid1Close = QtGui.QPushButton(self.groupBox2)
        font = QtGui.QFont()
        self.btLid1Close.setFont(font)
        self.btLid1Close.setObjectName(_fromUtf8("btLid1Close"))
        self.vboxlayout1.addWidget(self.btLid1Close)
        self.hboxlayout1.addWidget(self.groupBox2)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.groupBox6 = QtGui.QGroupBox(Isara2MaintWidget)
        self.groupBox6.setObjectName(_fromUtf8("groupBox6"))
        self.hboxlayout2 = QtGui.QHBoxLayout(self.groupBox6)
        self.hboxlayout2.setMargin(11)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.lblMessage = QtGui.QLabel(self.groupBox6)
        self.lblMessage.setWordWrap(False)
        self.lblMessage.setObjectName(_fromUtf8("lblMessage"))
        self.hboxlayout2.addWidget(self.lblMessage)
        self.vboxlayout.addWidget(self.groupBox6)
        self.groupBox = QtGui.QGroupBox(Isara2MaintWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btSoakTool = QtGui.QPushButton(self.groupBox)
        self.btSoakTool.setObjectName(_fromUtf8("btSoakTool"))
        self.horizontalLayout.addWidget(self.btSoakTool)
        self.btDryTool = QtGui.QPushButton(self.groupBox)
        self.btDryTool.setObjectName(_fromUtf8("btDryTool"))
        self.horizontalLayout.addWidget(self.btDryTool)
        spacerItem = QtGui.QSpacerItem(890, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.vboxlayout.addWidget(self.groupBox)
        self.groupBox13 = QtGui.QGroupBox(Isara2MaintWidget)
        self.groupBox13.setObjectName(_fromUtf8("groupBox13"))
        self.hboxlayout3 = QtGui.QHBoxLayout(self.groupBox13)
        self.hboxlayout3.setMargin(11)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.btAbort = QtGui.QPushButton(self.groupBox13)
        self.btAbort.setObjectName(_fromUtf8("btAbort"))
        self.hboxlayout3.addWidget(self.btAbort)
        self.btSafe = QtGui.QPushButton(self.groupBox13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btSafe.sizePolicy().hasHeightForWidth())
        self.btSafe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.btSafe.setFont(font)
        self.btSafe.setObjectName(_fromUtf8("btSafe"))
        self.hboxlayout3.addWidget(self.btSafe)
        self.btBack = QtGui.QPushButton(self.groupBox13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btBack.sizePolicy().hasHeightForWidth())
        self.btBack.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.btBack.setFont(font)
        self.btBack.setObjectName(_fromUtf8("btBack"))
        self.hboxlayout3.addWidget(self.btBack)
        self.btResetError = QtGui.QPushButton(self.groupBox13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btResetError.sizePolicy().hasHeightForWidth())
        self.btResetError.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.btResetError.setFont(font)
        self.btResetError.setObjectName(_fromUtf8("btResetError"))
        self.hboxlayout3.addWidget(self.btResetError)
        self.vboxlayout.addWidget(self.groupBox13)
        self.groupBox5_2 = QtGui.QGroupBox(Isara2MaintWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox5_2.sizePolicy().hasHeightForWidth())
        self.groupBox5_2.setSizePolicy(sizePolicy)
        self.groupBox5_2.setObjectName(_fromUtf8("groupBox5_2"))
        self.hboxlayout4 = QtGui.QHBoxLayout(self.groupBox5_2)
        self.hboxlayout4.setMargin(11)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.lblRegulationState = QtGui.QLabel(self.groupBox5_2)
        self.lblRegulationState.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRegulationState.setWordWrap(False)
        self.lblRegulationState.setObjectName(_fromUtf8("lblRegulationState"))
        self.hboxlayout4.addWidget(self.lblRegulationState)
        self.btRegulationOn = QtGui.QPushButton(self.groupBox5_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btRegulationOn.sizePolicy().hasHeightForWidth())
        self.btRegulationOn.setSizePolicy(sizePolicy)
        self.btRegulationOn.setObjectName(_fromUtf8("btRegulationOn"))
        self.hboxlayout4.addWidget(self.btRegulationOn)
        self.vboxlayout.addWidget(self.groupBox5_2)

        self.retranslateUi(Isara2MaintWidget)
        QtCore.QMetaObject.connectSlotsByName(Isara2MaintWidget)
        Isara2MaintWidget.setTabOrder(self.btPowerOn, self.btPowerOff)
        Isara2MaintWidget.setTabOrder(self.btPowerOff, self.btLid1Open)
        Isara2MaintWidget.setTabOrder(self.btLid1Open, self.btLid1Close)
        Isara2MaintWidget.setTabOrder(self.btLid1Close, self.btBack)

    def retranslateUi(self, Isara2MaintWidget):
        Isara2MaintWidget.setWindowTitle(_translate("Isara2MaintWidget", "Form1", None))
        self.groupBox5.setTitle(_translate("Isara2MaintWidget", "Arm Power", None))
        self.lblPowerState.setText(_translate("Isara2MaintWidget", "Power", None))
        self.btPowerOn.setText(_translate("Isara2MaintWidget", "Power On", None))
        self.btPowerOff.setText(_translate("Isara2MaintWidget", "Power Off", None))
        self.groupBox2.setTitle(_translate("Isara2MaintWidget", "Lid", None))
        self.btLid1Open.setText(_translate("Isara2MaintWidget", "Open", None))
        self.btLid1Close.setText(_translate("Isara2MaintWidget", "Close", None))
        self.groupBox6.setTitle(_translate("Isara2MaintWidget", "ISARA2 message", None))
        self.lblMessage.setText(_translate("Isara2MaintWidget", "Dummy message", None))
        self.groupBox.setTitle(_translate("Isara2MaintWidget", "Maintenance commands", None))
        self.btSoakTool.setText(_translate("Isara2MaintWidget", "Soak", None))
        self.btDryTool.setText(_translate("Isara2MaintWidget", "Dry", None))
        self.groupBox13.setTitle(_translate("Isara2MaintWidget", "Recovery Commands", None))
        self.btAbort.setText(_translate("Isara2MaintWidget", "Abort", None))
        self.btSafe.setText(_translate("Isara2MaintWidget", "Recover", None))
        self.btBack.setText(_translate("Isara2MaintWidget", "Back", None))
        self.btResetError.setText(_translate("Isara2MaintWidget", "Reset Error", None))
        self.groupBox5_2.setTitle(_translate("Isara2MaintWidget", "LN2 Regulation", None))
        self.lblRegulationState.setText(_translate("Isara2MaintWidget", "Regulation", None))
        self.btRegulationOn.setText(_translate("Isara2MaintWidget", "Regulation On", None))

